### ISSUE TITLE
NO PEERS 

### ISSUE THREAD

**Issue by kushalg-1212** [EpicCash/epic#77]
I installed the recent version on epic server on my windows server 
firewall is OFF 
still it just stucks with waiting for peers 

please suggest

**Comment by kushalg-1212** [comment]
Uncommitted seeds 
added below lines 
seeds = ["52.196.180.206:3414","1.158.39.147:3414","34.80.252.109:3414","88.156.253.31:3414","142.132.186.146:3414","95.217.197.180:3517","5.161.82.212:3414","95.216.215.107:3414","15.235.42.123:3414"]

still same

**Comment by Jualns** [comment]
Hey @kushalg-1212 

Can you try this configuration?
```toml
seeding_type = "List"

#If the seeding type is List, the list of peers to connect to can
#be specified as follows:
seeds = ["54.233.177.64:3414","3.218.126.145:3414"]
```
